export const jwtConstants = {
  secret: process.env.JWT_SECRET || "DO_NOT_USE_THIS_VALUE_IN_PRODUCTION_USE_ENV_VAR_INSTEAD_XYZ123",
  refreshSecret: process.env.JWT_REFRESH_SECRET || "DO_NOT_USE_THIS_VALUE_IN_PRODUCTION_USE_ENV_VAR_INSTEAD_REFRESH_XYZ123",
};
